### ISSUE TITLE
How do I run server and rest of docker-compose separately?

### ISSUE THREAD

**Issue by SashvDave** [TransformerOptimus/SuperCoder#104]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperCoder?

MacOS

### Which branch of SuperCoder are you using?

Main

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Hey, I want to be able to make changes to the go backend without having to re-run docker compose to see them. How would I go about doing so? or, is there something wrong on my end and this already works?

### Upload Error Log Content

n/a

**Comment by luciferlinx101** [comment]
You can build just the server using `docker-compose up -d --no-deps --build server` this is will let you build everything again.

**Comment by czezi** [comment]
@SashvDave 

Start the project by running the following command
```
docker compose up -d --build
```

Once you make any changes in the backend code, please use the following command for the changes to reflect in the server container.
```
docker compose up -d --no-deps --build server
```

**Comment by czezi** [comment]
Closing this issue as it's mostly on how you run docker, and answer should suffice.
