### ISSUE TITLE
Why not listed on the SWE-bench leaderboard?

### ISSUE THREAD

**Issue by panademo** [TransformerOptimus/SuperCoder#106]
See: https://github.com/swe-bench/experiments/tree/main

**Comment by neelayan7** [comment]
You can read about our results for SWE-Bench in this blog: https://superagi.com/supercoder-benchmarks-in-swe-bench-lite/

We have already submitted our results for SWE-Bench but I think they have not been updating it for the past few week due to some restructuring. It'll be added soon.
