### ISSUE TITLE
Some Questions on SuperCoder

### ISSUE THREAD

**Issue by BradKML** [TransformerOptimus/SuperCoder#39]
1. Is this WSL compatible (assuming Ubuntu is used with it)?
2. What is with Gitness for SuperCoder? Is it included in the Docker? https://github.com/harness/gitness
3. Where do the program files go? Even Git cloning won't get Docker to compose

**Comment by luciferlinx101** [comment]
Yeah should work on WSL or even in Windows you just need docker setup as everything is part of docker-compose. Gitness just one way of having a git remote server which is part of our docker-compose.You can see the files in the Code section in UI.
So just using `docker compose up --build` will you easily get started.

**Comment by BradKML** [comment]
But `docker compose up --build` does not point to any code directory or package server, no?

**Comment by luciferlinx101** [comment]
`docker compose up --build` will run the docker compose file in the root directory https://github.com/TransformerOptimus/SuperCoder/blob/main/docker-compose.yaml

**Comment by BradKML** [comment]
Note from future self: `docker-desktop` is the package to use in Chocolatey, NOT `docker-cli`
