### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by dumbsheep1990** [TransformerOptimus/SuperCoder#95]
Deployed on the server, the github verification when logging in jumps to localhost:3000. How to modify this address?

**Comment by luciferlinx101** [comment]
How are you running on server do you have k8 setup if so you can simply set APP_ENV=production for other cases you need to manually go and update the envs refer docker compose file to get an idea : https://github.com/TransformerOptimus/SuperCoder/blob/main/docker-compose.yaml

**Comment by luciferlinx101** [comment]
closing the issue as seems to be resolved feel free to reopen in case of need!
